version: '3'
services:
  api:
    container_name: web
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mitube
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_USER: root
    networks:
      - springboot-net
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    container_name: mitube-db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: mitube
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mitube
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'db', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      timeout: 5s
      retries: 10
    networks:
      - springboot-net
    ports:
      - "3307:3306"
    restart: always
networks:
  springboot-net: